let refundRules = {
    "asia": "No GP. In case of voluntary cancellation can be cancelled only due to Korean pax rule (flight from or to Korean airport for all pax nationality). Also med. issue can be applied if we have docs in English. Otherwise NC & only taxes after dep. can be refunded after fees deduction (We should apply for it via eform)",
    "allegiant": "Can be checked or cancelled on MMB before departure (RA in credits). After departure fully NR",
    "berlin": "Cancellable. In case of voluntary cancellation/no-show only taxes can be refunded with some fee",
    "blue panorama": "NC & fully NR (cancellation can be done only via letter => in 2017)) -> we can't do it )",
    "blue": "Cancellable. Assess RA -> via call. Proceed -> via email. No info about MC/death. no GP",
    "busan": "We can check RA or cancel before departure via MMB. After departure we should call a/l. Medical/death issues can be applied. GP up to 23:59 Korean time in the same day of purchase (maybe they use internal GDS system)",
    "cape": "Assess/proceed before dep. via MMB. If you have difficulties with MMB -> call. no GP. no Info about MC/death issues.",
    "cairo": "We can't check RA, cancel flight via call. Preferable communication type is via eform on their web. Approx. response time ~ 4 days. no GP. no Info about MC/death issues.",
    "cebu": "Depends on fare. Some flights are NC & only taxes after dep. (low fares, this info can be checked on confirmation). Some can be cancelled for travel funds. Cancellation for TF can be done via MMB, taxes after dep. -> only via call. Medical/death can be applied. GP - for US flights only according US law",
    "citilink": "fully NR. If promo fare -> also NC. no GP. no info about MC/death issues",
    "cobalt": "Cancellable. RA in case of cancellation/no-show = taxes amount - 20 EUR penalty per pap per flight. no GP. Med. issue can be applied",
    "condor": "If API -> can be checked/cancelled via API (check RA very carefully). Condor API GP (CX fee of 40 GBP if ticket costs more than 300 GBP CX fee of 25 GBP of CX fee if ticket costs less than 300 GBP. )",
    "eastarjet": "We can check RA or cancel before departure via MMB. After departure -> via call. Details about GP in Podio card. Med/death can be applied",
    "easyjet": "RA can be checked at taxes spreadsheet (taxes for dep. airport per pap). We can assess RA/cancel flight via call/chat. Med. issue can be applied. GP -> 24 hours after purchase, don't care about 7 days rule (RA minus some fee)",
    "eurowings": "NC & only taxes after dep. Agents usually not able to check RA. RA can be checked in confirmation. Applying for taxes via call(preferable)/eform. GP -> 24 hours after purchase (as for US law but for all routes) Also they don't care med issue",
    "flynas": "Can be cancelled on MMB. Check RA via call (don't know if RA can be checked via MMB for now). no GP. no info about med/death issues",
    "flybe": "Cancellable. Assess RA(RA = taxes - 25 GBP or 35 EUR)/cancel via call. GP 24 hours after purchase however RA in credits. Med/death issues can be applied",
    "frontier": "Can be cancelled on MMB but fully NR. GP for US flights as per US law. Med/death issues can be applied",
    "germanwings": "NC & only taxes after dep. Agents usually not able to check RA. RA can be checked in confirmation. Applying for taxes via call(preferable)/eform. GP -> 24 hours after purchase (as for US law but for all routes) Also they don't care med issue",
    "hawaiian": "Assess RA/cancel via call on pap's behalf. Usually providing full refund in travel credits in case of cancellation. GP can be applied as per US law. no info about med/death issues",
    "gol": "NC & fuly NR if directly",
    "hong kong": "Don't know. Need to call or check refund rules",
    "hong kong express": "Can be cancelled in agency portal but RA won't be displayed (terms of refunding ~ 2-3 month)",
    "HOP": "Cancellable. Can't say anything about RA. no GP. no info about Med./death issues",
    "interjet": "NC & fully NR even with UT. No Med./death refunds. No GP",
    "island": "The only thing I know is that it can be cancelled on MMB. Don't know if RA can be checked there. Not suitable working hours. There is web form on their web. no GP. no info about med/death issues",
    "japan": "Can be assessed/cancelled on MMB. no GP. no info about med/death issues",
    "jet2": "Cancellable but fully NR. no GP. no info about Med./death issues",
    "jetstar": "Cancellable but usually NR(taxes - penalty 50 USD per pap per flight usually negative). Med./death issue can be applied. no GP",
    "jetblue": "Can be cancelled on MMB (RA in credits for future use). Check RA via call. Fully NR if flight was booked via MP but better to attach screen from pkfare",
    "lingus": "Cancellable. RA = taxes amount minus 20 EUR penalty (per pap per flight). GP for US flights as per US law. Med./death issues can be applied",
    "malindo": "Cancellable. Assess/proceed via phone. no GP. Med/death issues can be applied",
    "monarch": "Can be cancelled only via call. RA before/after dep. = taxes - 25 GBP (penalty per booking => not per pap per flight). If taxes amount less than 25 GBP -> fully NR. If bigger -> better to call and confirm with a/l. Now it's declared bankrucy so all of this rules won't be applied till their return",
    "meridiana": "Assess/proceed via MMB. GP for US flights as per US law. no info about med./death issues",
    "nesma": "Don't know. Need to call or check refund rules",
    "nok": "NC & only taxes after dep. Check RA/apply for taxes via call or check RA in taxes spreadsheet. no GP. Med/death issues can be applied",
    "nordwind": "Don't know. Need to call or check refund rules",
    "nouvel": "Don't know. Need to call or check refund rules",
    "norwegian": "Cancellable. Assess RA/cancel via call(RA before/after dep. the same) (they don't care med. issue). Also if it's Norwegian Agency booking you can check RA in Norwe agency account (full amount of taxes) or cancel reservation. GP up to 4 hours after purchase for usual bookings and 24 hours after purchase for US flights (in more than 7 days prior dep.)",
    "olympic": "Cancellation/assessment via call. Cancellable, RA in case of cancellation/no-show = taxes - 20 EUR penalty (don't know if per pap per flight or for whole booking). no GP. no info about med./death issues",
    "peach": "Cancellable (via MMB) but fully NR (because of very hight fee on taxes refunds). no GP. Med./death can be applied",
    "pobeda": "Cancellable but fully NR. no GP. Med/death issues can be applied",
    "pegasus": "If via API -> we cancel/apply for tax after dep./check RA via API (watch carefully if you cancel check-in or not), directly -> via call. GP 20 min only via MMB )) Med/death issues only before dep. time",
    "ryan": "NC & fully NR. no GP (only some changes can be done withing 24 hours after purchase). Medical(serious illness)/death can be applied",
    "scoot": "NC & fully NR. The legend says that we can request some TR after dep. minus some fee. But who cares? Very long hold time and it's easier to consider this a/l as fully NR. no GP. no Med/death issues",
    "sky": "Can be cancelled via MMB. RA = full amount of taxes (taxes amount can be checked on MMB) in green square )). Need to call after dep. RA the same before/after dep. no GP. Med/death issues can be applied",
    "sky express": "Assess RA: check fare type at confirmation and check fare rules on web. Cancellation possible via MMB but RA won't be displayed. GP 1 hour after purchase. No info about med/death issues",
    "spicejet": "Assess RA/cancellation via MMB. TR after dep. via call (taxes). no GP. Med/death issues can be applied",
    "spirit": "Can be cancelled/checked on MMB up to check-in. Fully NR after dep. GP as per US law. Med. issue can be applied only before dep. ",
    "sriwijaya": "Don't know. Need to call or check refund rules",
    "sunexpress": "Assess RA/cancellation before/after dep. via MMB. Pure happiness. no GP. no info about med./death issues",
    "southwest": "Can be cancelled/checked on MMB. RA in travel funds which we don't cover. They don't care med. issues. Also if we going to cancel/check RA for SW flights only -> no Margin or HF. GP as per US law",
    "tiger": "NC & fully NR. Med./death can be applied. no GP",
    "thai smile": "NC. Only taxes after dep. with some fee. no GP. Med/death issues can be applied",
    "tway": "We can assess RA/cancel flight before dep. on MMB (don't know how can be done assessment for now). Better to check GP option with a/l directly. No info about med./death issues",
    "transavia": "Cancellation/TR after dep./assess RA via call (very short hold time). no GP. no med. issue (only pax death)",
    "tui": "Almost always fully NR because of their refund penalty on taxes. Don't know if it's cancellable or not because different agents provide different info. no GP. no Med/death issues",
    "vanilla": "Cancellable (on MMB) but fully NR (because of very hight fee on taxes refunds). no GP. Med/death can be applied",
    "vietjet": "NC & fully NR because we need to apply for cancellation/refunds via origin email (we can't do that)",
    "virgin": "Cancellable. Assess RA/TR after dep./cancellation via call. GP as per US law for US flights. Med./death can be applied",
    "volaris": "NC & fully NR. GP for US flights as per US law. no info about Med/death issues",
    "viva columbia": "Check RA via call. Cancel/TR after dep via email (pap's LoC and pp copy needed). GP for US flights as per US law. Med/death can be applied",
    "volotea": "Don't know. Need to call or check refund rules",
    "vueling": "NC & only taxes after dep. Check RA/apply for TR via call. GP 2 hours after purchase. Med/death can be applied",
    "wamos": "fully NR. Don't know cancellable or not",
    "westjet": "if directly -> cancellable, NR or credits, RA can be assessed on MMB by pressing 'cancel' button, a booking won't be cancelled at once, the system will ask to re-confirm CX",
    "wizz": "Cancellation more than 14 days before dep. -> RA = full fare - 60 EUR penalty per pap per flight. Cancellation withing 14 days prior dep./applying for taxes after dep. -> RA = basic fare (full fare - additional services) - 80 EUR penalty  per pap per flight --> almost always NR in that case. no GP. Med/death can be applied",
    "wow": "cancellable. Taxes before/after dep. in full amount. Taxes can be checked on MMB. GP rules in Podio card. Med/death issues can be applied"
};